### PR TITLE
Add Basic auth functionality

### PR DESCRIPTION
**Pull request by borisnaydis**
This PR adds Basic Auth functionality to the client.

Rationale:
We use New Relic at work to collect metrics. However, we depend on third-party endpoints secured by basic authentication. Currently, NRI Prometheus does not provide the ability to specify a username and password.

Implementation details:
This PR adds a `basic_auth_file` configuration setting and `basicAuthRoundTripper`, which allow specifying a file that would be read on each request similarly to `bearerAuthFileRoundTripper`. The format of the credentials file is `<username>:<password>`.

### CODE REVIEW

**Comment by sudiptad2017** [comment]
Great work @borisnaydis! This will help with our use case of exposing prometheus data from Confluent monitoring endpoints (that use Basic authorization) to NewRelic.

**Comment by davidgit** [comment]
Hi @borisnaydis,

We plan to work on `nri-prometheus` in the mid-term. We'll come back to you as soon as we've refined and estimated the effort

Thanks!

**Comment by borisnaydis** [comment]
Hi @davidgit. Could you give us an approximate timeline of when the change can make it through? Also, is there anything we can help with?

**Comment by bparker695** [comment]
@davidgit, any updates on this by chance?

**Comment by roobre** [comment]
Hey @bparker695, thanks a lot for your contribution!
Implementing more advanced features into `nri-prometheus` is something we're considering internally, but we still have not taken a firm decision about which direction we want to move towards with this codebase. We have scheduled some efforts in the next months to offer better support for monitoring services exporting Prometheus metrics, but until we figure out the details I'm afraid that we will not be able to accept your PR.

If you want, we can keep it open until that happens so it is easier to iterate later.

BR and thanks again for your efforts!

**Comment by mebobby2** [comment]
@davidgit, any updates on this? I have the exact use case (scraping Confluent metric endpoints) and would be keen to see this get added to trunk.

**Comment by davidgit** [comment]
We appreciate you taking the time to bring this to our attention. After reviewing this issue, we are unable to commit on a timeline to resolution because we are working on a new solution to monitor Prometheus metrics.

We encourage community contributions and are happy to collaborate on design proposals and pull requests. See our PR guidelines in the README. If you have any further questions or comments about this, please let us know by replying to this issue.

**Pull request closed without merging**
