### PR TITLE
Fix: NaN values produce invalid json

### PR DESCRIPTION
**Pull request by alejandrodnm**
Some metrics which are NaN cause the sdk to produce an invalid json, the marshaling of the json doesn't fail and it's a problem in the telemetry sdk. I already open an issue in their repo.

https://github.com/newrelic/go-telemetry-sdk/issues/2

This invalid json was being sent to newrelic, and because it couldn't be parsed, the whole metrics batch was discarded. 

This PR checks the values for NaN or Inf before sending them to the sdk.

### CODE REVIEW

**Comment by jorikvdwerf** [comment]
Hm, if the library has been fixed, we will not need to have this check in place, right? Can we try to have them fix it asap (or even do it for them), and not add this additional check?

**Comment by alejandrodnm** [comment]
@douglascamata actually this NaNs won't be sent. Do you think we should send them as nulls? what do you think @jorikvdwerf.

I really don't know the implications or the UX of sending them as null.

I already ping the sdk team for an ETA to see if they are going to fix it on their end.

**Comment by douglascamata** [comment]
I would expect them to be present as null because the metrics are technically there, but only have this NaN value for the moment. To me it sounds different from not having the metrics at all.

**Comment by alejandrodnm** [comment]
This was fixed directly in the SDK 

https://github.com/newrelic/newrelic-telemetry-sdk-go/pull/3

**Pull request closed without merging**
