### PR TITLE
Chore/move charts

### PR DESCRIPTION
**Pull request by paologallinaharbur**
Moving nri-prometheus and load-generator charts to a new charts folder

### CODE REVIEW

**Review by roobre — APPROVED** [review]
🙈

**Review by kang-makes — COMMENTED** [review]
```
% git checkout chore/moveCharts
branch 'chore/moveCharts' set up to track 'origin/chore/moveCharts'.
Switched to a new branch 'chore/moveCharts'

% diff --recursive {../helm-charts/,}charts/nri-prometheus/

% diff --recursive {../helm-charts/,}charts/nri-prometheus/ | wc -l
0
```
It does not allow me to give you a comment on a "file renamed without changes".

[load-generator's Chart.yaml](https://github.com/newrelic/nri-prometheus/blob/1a34ce7a83219a15150f9c898b58d14a07d17357/charts/load-test-environment/Chart.yaml) should have a version with `-devel` so it is not shown as a release from us to customers to use it.

LGTM tho.

**Comment by paologallinaharbur** [comment]
I had in a different branch, but you are right, better to add it know just in case

**Comment by kang-makes** [comment]
Screenshot 2022-03-24 at 13 31 42

I see both of the commits. What do you mean with you have it in a different branch?

**Comment by paologallinaharbur** [comment]
In a branch I have locally that is on the top of this 😃

**Pull request merged**
