### PR TITLE
do not scrape pods that are completed

### PR DESCRIPTION
**Pull request by anandkumarpatel**
Pods that are completed and will never be restarted should not be scrapped because there is no process alive to handle the call. 

This PR add a check for pod completion to the `isObjectScrapable` function. 

I made it a switch statement in case there is a need to use object-specific keys to determine scrapability in the future. 

[Pod Phases doc](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase)
[Restart Policy doc](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy)

Fix for: https://github.com/newrelic/nri-prometheus/issues/150

### CODE REVIEW

**Comment by paologallinaharbur** [comment]
We are currently modifying the same snippet of the code you are modifying.
Therefore likely we will need to rebase this PR once the one enabling endpoints gets merged.
By the way thanks for the contribution!

**Comment by anandkumarpatel** [comment]
Hey @paologallinaharbur I am fine with rebasing. I took a look at the other PR and they are compatible. I only modify `isObjectScrapable` and look like the other PR does not modify that function. 

But would it be possible to merge this one first? Seems like the other one might be a breaking change. I'll be happy to rebase into the other branch as well to make it possible!

**Comment by paologallinaharbur** [comment]
Closing since there has been no activity. 
Feel free to propose a new one or reopen this one :)

**Comment by anandkumarpatel** [comment]
@paologallinaharbur Created new one here: https://github.com/newrelic/nri-prometheus/pull/212

**Pull request closed without merging**
